### ISSUE TITLE
SocialNetwork fails to compile

### ISSUE THREAD

**Issue by andrewtyped** [fekberg/Pluralsight#1]
Hi,
   The SocialNetwork.Api project has a duplicated method in ProfilesController. The SocialNetwork.OAuth project is missing implementations for methods in the SocialNetwork.OAuth.Configuration namespace. This all prevents the solution from compiling. I have a pull request ready to go which removes the duplicate methods and adds some NotImplementedExceptions, if you want it.

**Comment by fekberg** [comment]
Thanks @andrewtyped, these errors are intentional, as you follow along the course you will add the implementations/fix the issues, but I'll merge the PR, will make it easier to as a starting point. Thanks!
